#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace HelloDev.Logging.Editor
{
    public static class LoggerIdGenerator
    {
        private const string DefaultOutputPath = "Assets/HelloDev/com.hellodev.utils/Runtime/Scripts/Logging/Generated/LogIds.cs";
        private const string DefaultNamespace = "HelloDev.Logging";

        public static void GenerateForSettings(
            LoggerSettings_SO settings,
            string outputPath = null,
            string namespaceName = null)
        {
            if (settings == null || settings.Systems == null || settings.Systems.Count == 0)
            {
                Debug.LogError("[LoggerIdGenerator] LoggerSettings_SO is null or has no systems.");
                return;
            }

            string path = string.IsNullOrWhiteSpace(outputPath) ? DefaultOutputPath : outputPath;
            string ns = string.IsNullOrWhiteSpace(namespaceName) ? DefaultNamespace : namespaceName;

            EnsureDirectoryExists(path);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by LoggerIdGenerator from LoggerSettings_SO.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    public static class LogIds");
            sb.AppendLine("    {");

            var usedIdentifiers = new HashSet<string>();

            foreach (var system in settings.Systems)
            {
                if (string.IsNullOrEmpty(system.SystemId)) continue;

                string identifier = SanitizeIdentifier(system.SystemId);

                if (!usedIdentifiers.Add(identifier))
                {
                    Debug.LogWarning(
                        $"[LoggerIdGenerator] Duplicate identifier '{identifier}' from SystemId '{system.SystemId}'. Skipping.");
                    continue;
                }

                sb.AppendLine($"        public const string {identifier} = \"{system.SystemId}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(path, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[LoggerIdGenerator] Generated {usedIdentifiers.Count} constants at {path}");
        }

        private static void EnsureDirectoryExists(string filePath)
        {
            string directory = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);
        }

        private static string SanitizeIdentifier(string systemId)
        {
            var sb = new StringBuilder(systemId.Length);
            foreach (char c in systemId)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
                else
                    sb.Append('_');
            }

            // Prefix with underscore if it starts with a digit
            if (sb.Length > 0 && char.IsDigit(sb[0]))
                sb.Insert(0, '_');

            return sb.ToString();
        }
    }
}
#endif